Repository 99lash/BagyoAlerto, pull requests merged in 2025-08, with the labels that each got.

#51 Change the message in footer
  checklist.html
  emergency.html
  guide.html
  index.html
Labels: chore

#52 Initial/guide page
  guide.html
  styles/index.css
Labels: feature

#58 chore: remove the extra botton in emergency cards
  emergency.html
  styles/index.css
Labels: chore

#62 made the button into a foreground color
  styles/index.css
Labels: dashboard page

#66 setup: data-schemas
  docs/DATA_SCHEME.md
Labels: documentation

#67 copy contact to clipboard & call contact action functionality
  emergency.html
  scripts/features/emergency-contacts.js
  scripts/index.js
  styles/index.css
Labels: feature, chore, emergency page, UX

#68 feat: weather api integration + initial alert reminder
  index.html
  scripts/core/geolocation.js
  scripts/core/weather.js
  scripts/features/alert.js
  scripts/features/dashboard.js
  scripts/features/emergency-contacts.js
  scripts/index.js
  scripts/utils/date.js
  styles/index.css
Labels: feature, dashboard page, weather, api

#76 fix: window location pathname cannot read '/'
  scripts/index.js
Labels: bug, fix

#93 chore: fixing print-page.html
  styles/index.css
Labels: chore, emergency page

#89 Chore: dashboard and icon
  checklist.html
  emergency.html
  guide.html
  styles/index.css
Labels: chore
