Repository 99lash/BagyoAlerto, pull requests merged in 2025-07, with the labels that each got.

#7 setup: css boilerplate
  index.html
  styles/index.css
Labels: chore

#13 docs: fix main features TOC link
  README.md
Labels: bug

#15 partial: footer-layout-design?
  .hintrc
  checklist.html
  emergency.html
  guide.html
  index.html
  styles/index.css
Labels: enhancement

#20 Set up/brand logo
  assets/img/android-chrome-192x192.png
  assets/img/android-chrome-512x512.png
  assets/img/apple-touch-icon.png
  assets/img/favicon-16x16.png
  assets/img/favicon-32x32.png
  assets/img/site.webmanifest
  favicon.ico
Labels: enhancement, help wanted, good first issue

#23 bug: fix wrong placement of container class
  checklist.html
  emergency.html
  guide.html
  index.html
  styles/index.css
Labels: bug, fix

#25 added the necessary code for it to be sticky
  styles/index.css
Labels: fix
